### PR TITLE
Add massive eslint

### PR DESCRIPTION
**Pull request by slimlime**
Probably a few things fell through the cracks

Time to rewrite.

that weird g transform thing with all the nested functions takes a while to drill down the proper types
Datum any

#6

### CODE REVIEW

**Review by seant1 — APPROVED** [review]
Nice types, lint, docs

**Comment by slimlime** [comment]
Sonarcloud issue
minor A--rating new code quality
self-descriptive semantics worth more than the 10 min tech debt

possible fix using self-descriptive function call instead to wrap that functionality

**Comment by slimlime** [comment]
Thanks for reviewing @seant1 🙌

**Review by slimlime — COMMENTED** [review]
lazy branch naming merging convention

**Review by slimlime — COMMENTED** [review]
approves this message

**Pull request merged**
